[tool.poetry]
name = "tododjango"
version = "0.1.0"
description = ""
authors = ["21Sirius <21siriusss@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.7"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
